temp=int(input("Enter temperature in celsius: "))
f=((temp * 9/5)+32)
print("Temperature in Farheniet: ",f)
temp=int(input("Enter temperature in Farheniet: "))
f=(temp - 32)*(5/9)
print("Temperature in celsius",f)
